 spring:
  #Configuración MySQL
  datasource:
   url: jdbc:mysql://localhost:3306/newsinstantly?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
   username: root
   password: root
   driver-class-name: com.mysql.cj.jdbc.Driver
  #Configuración Creación de tablas (Hibernate)
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
   properties:
    hibernate:
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: newsinstantly7@gmail.com
    password: equipo7egg
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
  #Que thymeleaf no guarde datos en cache
  thymeleaf:
   cache: false
 server:
   port: 8080
